GET {{host}}/circles/ HTTP/1.1
content-type: application/json

###
POST {{host}}/circles/ HTTP/1.1
content-type: application/json

{
    "name":"nombre de circulo 1",
    "about":"circulo ejemplo",
    "slug_name":"ce1"
}
###
PUT {{host}}/circles/1/ HTTP/1.1
content-type: application/json

{
    "name":"nombre de circulo 1.1",
    "about":"circulo ejemplo",
    "slug_name":"ce1_1"
}
###
PATCH {{host}}/circles/1/ HTTP/1.1
content-type: application/json

{
    "name":"nombre de circulo 1.1"
}
###
DELETE {{host}}/circles/1/ HTTP/1.1
content-type: application/json

{
    "name":"nombre de circulo 1.1"
}
###
POST {{host}}/users/login/ HTTP/1.1
content-type: application/json

{
    "email": "xxxxx",
    "password": "xxxxx"
}
###
# USERS

POST {{host}}/users/signup/ HTTP/1.1
content-type: application/json

{
    "email": "xxx",
    "username": "pepe4",
    "password": "xxxx",
    "password_confirmation": "xxxxx",
    "first_name":"pepe2",
    "last_name":"pecas"
}
###
POST {{host}}/users/verify/ HTTP/1.1
content-type: application/json

{
    "token": "eyJ0eaasaiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGVwZTQiLCJleHAiOjE2MjQ3MzkzNzgsInR5cGUiOiJlbWFpbF9jb25maXJtYXRpb24ifQ._zxHOf-cogirXSkobO8Jieipzm5acDOqRz3EagUTN44"
}