# Generated by Django 3.2.4 on 2021-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=140, unique=True, verbose_name='slug name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures/', verbose_name='circle picture')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='verified circles are officials communities', verbose_name='verified circle')),
                ('is_public', models.BooleanField(default=False, help_text='public circle')),
                ('is_limited', models.BooleanField(default=False, help_text='limited circles')),
                ('limit', models.PositiveIntegerField(default=0, help_text='limit')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
