# Generated by Django 3.2.4 on 2021-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='about',
            field=models.CharField(default='', max_length=255, verbose_name='circle description'),
            preserve_default=False,
        ),
    ]
