# Generated by Django 2.0.10 on 2021-08-04 21:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_invitation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitation',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
