# Generated by Django 2.0.10 on 2021-08-04 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20210804_2121'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitation',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User that uses the code to enter the circle', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
