# Generated by Django 2.0.10 on 2021-08-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='offered_bin',
            new_name='offered_in',
        ),
    ]
