# Generated by Django 2.0.10 on 2021-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20210805_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='deperture_date',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='deperture_location',
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(default='aqui', max_length=255),
            preserve_default=False,
        ),
    ]
